---
name: module3_task3
run-name: module3_task3
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - master
    tags:
      - "*"
  schedule:
    - cron: "30 5,17 * * *"
permissions:
  contents: write
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup
        run: ./setup.sh
        working-directory: module3_task3

      - name: Build
        run: sudo make build
        working-directory: module3_task3

      - name: Test validation
        id: test
        run: sudo make test
        working-directory: module3_task3

      - name: Package
        if: steps.test.outputs.exit_code == 0
        run: sudo make package
        working-directory: module3_task3

      - name: 1.0.0
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            DEPLOY.md
            awesome-website.zip
